"""WhisperX extra alignment models (vendored from SoniTranslate, MIT)."""

INVERTED_LANGUAGES = {
    "ar": "Arabic (ar)",
    "zh": "Chinese - Simplified (zh-CN)",
    "cs": "Czech (cs)",
    "da": "Danish (da)",
    "nl": "Dutch (nl)",
    "en": "English (en)",
    "fi": "Finnish (fi)",
    "fr": "French (fr)",
    "de": "German (de)",
    "el": "Greek (el)",
    "he": "Hebrew (he)",
    "hu": "Hungarian (hu)",
    "it": "Italian (it)",
    "ja": "Japanese (ja)",
    "ko": "Korean (ko)",
    "fa": "Persian (fa)",
    "pl": "Polish (pl)",
    "pt": "Portuguese (pt)",
    "ru": "Russian (ru)",
    "es": "Spanish (es)",
    "tr": "Turkish (tr)",
    "uk": "Ukrainian (uk)",
    "ur": "Urdu (ur)",
    "vi": "Vietnamese (vi)",
    "hi": "Hindi (hi)",
    "id": "Indonesian (id)",
    "bn": "Bengali (bn)",
    "te": "Telugu (te)",
    "mr": "Marathi (mr)",
    "ta": "Tamil (ta)",
    "jw": "Javanese (jw|jv)",
    "ca": "Catalan (ca)",
    "ne": "Nepali (ne)",
    "th": "Thai (th)",
    "sv": "Swedish (sv)",
    "am": "Amharic (am)",
    "cy": "Welsh (cy)",
    "et": "Estonian (et)",
    "hr": "Croatian (hr)",
    "is": "Icelandic (is)",
    "ka": "Georgian (ka)",
    "km": "Khmer (km)",
    "sk": "Slovak (sk)",
    "sq": "Albanian (sq)",
    "sr": "Serbian (sr)",
    "az": "Azerbaijani (az)",
    "bg": "Bulgarian (bg)",
    "gl": "Galician (gl)",
    "gu": "Gujarati (gu)",
    "kk": "Kazakh (kk)",
    "kn": "Kannada (kn)",
    "lt": "Lithuanian (lt)",
    "lv": "Latvian (lv)",
    "mk": "Macedonian (mk)",
    "ml": "Malayalam (ml)",
    "ms": "Malay (ms)",
    "ro": "Romanian (ro)",
    "si": "Sinhala (si)",
    "su": "Sundanese (su)",
    "sw": "Swahili (sw)",
    "af": "Afrikaans (af)",
    "bs": "Bosnian (bs)",
    "la": "Latin (la)",
    "my": "Myanmar Burmese (my)",
    "no": "Norwegian (no|nb)",
    "zh-TW": "Chinese - Traditional (zh-TW)",
    "tl": "Tagalog (tl)",
}

EXTRA_ALIGN = {
    "id": "indonesian-nlp/wav2vec2-large-xlsr-indonesian",
    "bn": "arijitx/wav2vec2-large-xlsr-bengali",
    "mr": "sumedh/wav2vec2-large-xlsr-marathi",
    "ta": "Amrrs/wav2vec2-large-xlsr-53-tamil",
    "jw": "cahya/wav2vec2-large-xlsr-javanese",
    "ne": "shniranjan/wav2vec2-large-xlsr-300m-nepali",
    "th": "sakares/wav2vec2-large-xlsr-thai-demo",
    "sv": "KBLab/wav2vec2-large-voxrex-swedish",
    "am": "agkphysics/wav2vec2-large-xlsr-53-amharic",
    "cy": "Srulikbdd/Wav2Vec2-large-xlsr-welsh",
    "et": "anton-l/wav2vec2-large-xlsr-53-estonian",
    "hr": "classla/wav2vec2-xls-r-parlaspeech-hr",
    "is": "carlosdanielhernandezmena/wav2vec2-large-xlsr-53-icelandic-ep10-1000h",
    "ka": "MehdiHosseiniMoghadam/wav2vec2-large-xlsr-53-Georgian",
    "km": "vitouphy/wav2vec2-xls-r-300m-khmer",
    "sk": "infinitejoy/wav2vec2-large-xls-r-300m-slovak",
    "sq": "Alimzhan/wav2vec2-large-xls-r-300m-albanian-colab",
    "sr": "dnikolic/wav2vec2-xlsr-530-serbian-colab",
    "az": "nijatzeynalov/wav2vec2-large-mms-1b-azerbaijani-common_voice15.0",
    "bg": "infinitejoy/wav2vec2-large-xls-r-300m-bulgarian",
    "gl": "ifrz/wav2vec2-large-xlsr-galician",
    "gu": "Harveenchadha/vakyansh-wav2vec2-gujarati-gnm-100",
    "kk": "aismlv/wav2vec2-large-xlsr-kazakh",
    "kn": "Harveenchadha/vakyansh-wav2vec2-kannada-knm-560",
    "lt": "DeividasM/wav2vec2-large-xlsr-53-lithuanian",
    "lv": "anton-l/wav2vec2-large-xlsr-53-latvian",
    "mk": "",
    "ml": "gvs/wav2vec2-large-xlsr-malayalam",
    "ms": "",
    "ro": "anton-l/wav2vec2-large-xlsr-53-romanian",
    "si": "IAmNotAnanth/wav2vec2-large-xls-r-300m-sinhala",
    "su": "cahya/wav2vec2-large-xlsr-sundanese",
    "sw": "",
    "af": "",
    "bs": "",
    "la": "",
    "my": "",
    "no": "NbAiLab/wav2vec2-xlsr-300m-norwegian",
    "zh-TW": "jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn",
    "as": "",
    "eu": "",
    "ha": "infinitejoy/wav2vec2-large-xls-r-300m-hausa",
    "ht": "",
    "hy": "infinitejoy/wav2vec2-large-xls-r-300m-armenian",
    "lo": "",
    "mg": "",
    "mn": "tugstugi/wav2vec2-large-xlsr-53-mongolian",
    "mt": "carlosdanielhernandezmena/wav2vec2-large-xlsr-53-maltese-64h",
    "pa": "kingabzpro/wav2vec2-large-xlsr-53-punjabi",
    "ps": "aamirhs/wav2vec2-large-xls-r-300m-pashto-colab",
    "sl": "anton-l/wav2vec2-large-xlsr-53-slovenian",
    "sn": "",
    "so": "",
    "tg": "",
    "tk": "",
    "tt": "anton-l/wav2vec2-large-xlsr-53-tatar",
    "uz": "",
    "yo": "ogbi/wav2vec2-large-mms-1b-yoruba-test",
    "tl": "Khalsuu/filipino-wav2vec2-l-xls-r-300m-official",
}

__all__ = ["EXTRA_ALIGN", "INVERTED_LANGUAGES"]
